### ISSUE TITLE
Is posible to use a previous react-native-fs dependecy? currently is broken

### ISSUE THREAD

**Issue by sir-gon** [sponk-pl/react-native-realm-cache-image#1]
Currently, react-native-fs (2.0.1-rc.2) can't compile on iOS, and have a very weird dependency (in cocoapods) with deprecated (0.11.0) React integration.

I'm submitted an [issue](https://github.com/johanneslumpe/react-native-fs/issues/194), but I haven't answers ...

Is posible to make something to support 1.5.1 stable release of react-native-fs ?

**Comment by mpochron** [comment]
At least I tested this package on react native with version 0.35 and it worked. I prefer that you do update version to like that.

Alternative way:
U can try to get older plugin react-native-fs (1.5.1) with using fork and editing package.json.

**Comment by mpochron** [comment]
I will close.
